<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="5" failed="4" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-17T23:47:57 TRT" name="All Test Suite" finished-at="2023-02-17T23:49:58 TRT" duration-ms="120419">
    <groups>
    </groups>
    <test started-at="2023-02-17T23:47:57 TRT" name="Package level Test" finished-at="2023-02-17T23:49:58 TRT" duration-ms="120419">
      <class name="com.exelenter.class03._01_SoftAssertRecap">
        <test-method signature="testCase()[pri:0, instance:com.exelenter.class03._01_SoftAssertRecap@1e9e725a]" started-at="2023-02-17T23:48:56 TRT" name="testCase" finished-at="2023-02-17T23:48:56 TRT" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.exelenter.class03._01_SoftAssertRecap.testCase(_01_SoftAssertRecap.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
      </class> <!-- com.exelenter.class03._01_SoftAssertRecap -->
      <class name="com.exelenter.class02._01_ValidationTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:47:57 TRT" name="setUp" finished-at="2023-02-17T23:48:04 TRT" duration-ms="6388" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="titleValidation()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:04 TRT" name="titleValidation" finished-at="2023-02-17T23:48:04 TRT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:04 TRT" name="tearDown" finished-at="2023-02-17T23:48:06 TRT" duration-ms="2260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:06 TRT" name="setUp" finished-at="2023-02-17T23:48:12 TRT" duration-ms="6462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="logoValidation()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:12 TRT" name="logoValidation" finished-at="2023-02-17T23:48:12 TRT" duration-ms="44" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:12 TRT" name="tearDown" finished-at="2023-02-17T23:48:15 TRT" duration-ms="2180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:15 TRT" name="setUp" finished-at="2023-02-17T23:48:19 TRT" duration-ms="4735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLoginTest()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:19 TRT" name="validLoginTest" finished-at="2023-02-17T23:48:27 TRT" duration-ms="7415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._01_ValidationTests@6385cb26]" started-at="2023-02-17T23:48:27 TRT" name="tearDown" finished-at="2023-02-17T23:48:29 TRT" duration-ms="2253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.class02._01_ValidationTests -->
      <class name="com.exelenter.class02._03_TitleAndLogoValidation">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:48:56 TRT" name="setUp" finished-at="2023-02-17T23:49:02 TRT" duration-ms="6230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:49:02 TRT" name="openBrowser" finished-at="2023-02-17T23:49:11 TRT" duration-ms="8943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="titleValidation()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:49:11 TRT" name="titleValidation" finished-at="2023-02-17T23:49:11 TRT" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title does not match! expected [Exelenter Project!!!] but found [Exelenter Project]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title does not match! expected [Exelenter Project!!!] but found [Exelenter Project]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.exelenter.class02._03_TitleAndLogoValidation.titleValidation(_03_TitleAndLogoValidation.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:49:11 TRT" name="quitBrowser" finished-at="2023-02-17T23:49:14 TRT" duration-ms="2730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:49:14 TRT" name="tearDown" finished-at="2023-02-17T23:49:16 TRT" duration-ms="2007" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="logoValidation()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c]" started-at="2023-02-17T23:49:16 TRT" name="logoValidation" finished-at="2023-02-17T23:49:16 TRT" depends-on-methods="com.exelenter.class02._03_TitleAndLogoValidation.titleValidation" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method _03_TitleAndLogoValidation.logoValidation()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method _03_TitleAndLogoValidation.logoValidation()[pri:0, instance:com.exelenter.class02._03_TitleAndLogoValidation@28c4711c] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoValidation -->
      </class> <!-- com.exelenter.class02._03_TitleAndLogoValidation -->
      <class name="com.exelenter.class02._04_Task1">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._04_Task1@59717824]" started-at="2023-02-17T23:49:16 TRT" name="setUp" finished-at="2023-02-17T23:49:23 TRT" duration-ms="6831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.exelenter.class02._04_Task1@59717824]" started-at="2023-02-17T23:49:23 TRT" name="openBrowser" finished-at="2023-02-17T23:49:30 TRT" duration-ms="7332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="dashboardLogoValidation()[pri:0, instance:com.exelenter.class02._04_Task1@59717824]" started-at="2023-02-17T23:49:30 TRT" name="dashboardLogoValidation" finished-at="2023-02-17T23:49:32 TRT" duration-ms="2400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardLogoValidation -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.exelenter.class02._04_Task1@59717824]" started-at="2023-02-17T23:49:32 TRT" name="quitBrowser" finished-at="2023-02-17T23:49:34 TRT" duration-ms="2231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._04_Task1@59717824]" started-at="2023-02-17T23:49:34 TRT" name="tearDown" finished-at="2023-02-17T23:49:37 TRT" duration-ms="2004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.class02._04_Task1 -->
      <class name="com.exelenter.class02._02_AssertDemo">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:29 TRT" name="setUp" finished-at="2023-02-17T23:48:33 TRT" duration-ms="4031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:33 TRT" name="openBrowser" finished-at="2023-02-17T23:48:35 TRT" duration-ms="2317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="validLoginTest()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:35 TRT" name="validLoginTest" finished-at="2023-02-17T23:48:37 TRT" duration-ms="1848" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:37 TRT" name="quitBrowser" finished-at="2023-02-17T23:48:39 TRT" duration-ms="2127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:39 TRT" name="tearDown" finished-at="2023-02-17T23:48:41 TRT" duration-ms="2008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:41 TRT" name="setUp" finished-at="2023-02-17T23:48:45 TRT" duration-ms="3739" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:45 TRT" name="openBrowser" finished-at="2023-02-17T23:48:51 TRT" duration-ms="6136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="invalidLoginTest()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:51 TRT" name="invalidLoginTest" finished-at="2023-02-17T23:48:52 TRT" duration-ms="319" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Message Error is incorrect. expected [Password cannot be empty1] but found [Password cannot be empty]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Message Error is incorrect. expected [Password cannot be empty1] but found [Password cannot be empty]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.exelenter.class02._02_AssertDemo.invalidLoginTest(_02_AssertDemo.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:52 TRT" name="quitBrowser" finished-at="2023-02-17T23:48:54 TRT" duration-ms="2230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._02_AssertDemo@38364841]" started-at="2023-02-17T23:48:54 TRT" name="tearDown" finished-at="2023-02-17T23:48:56 TRT" duration-ms="2008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.class02._02_AssertDemo -->
      <class name="com.exelenter.class02._05_SoftAssertDemo">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.class02._05_SoftAssertDemo@146044d7]" started-at="2023-02-17T23:49:37 TRT" name="setUp" finished-at="2023-02-17T23:49:39 TRT" duration-ms="2631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.exelenter.class02._05_SoftAssertDemo@146044d7]" started-at="2023-02-17T23:49:39 TRT" name="openBrowser" finished-at="2023-02-17T23:49:43 TRT" duration-ms="3805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="softAssertionTest()[pri:0, instance:com.exelenter.class02._05_SoftAssertDemo@146044d7]" started-at="2023-02-17T23:49:43 TRT" name="softAssertionTest" finished-at="2023-02-17T23:49:53 TRT" duration-ms="10493" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Login logo is not displayed. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Login logo is not displayed. expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.exelenter.class02._05_SoftAssertDemo.softAssertionTest(_05_SoftAssertDemo.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- softAssertionTest -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.exelenter.class02._05_SoftAssertDemo@146044d7]" started-at="2023-02-17T23:49:53 TRT" name="quitBrowser" finished-at="2023-02-17T23:49:56 TRT" duration-ms="2227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.class02._05_SoftAssertDemo@146044d7]" started-at="2023-02-17T23:49:56 TRT" name="tearDown" finished-at="2023-02-17T23:49:58 TRT" duration-ms="2006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.class02._05_SoftAssertDemo -->
    </test> <!-- Package level Test -->
  </suite> <!-- All Test Suite -->
</testng-results>
